# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/keeprom.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 637)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.label.setObjectName("label")
        self.eepromChooser = QtWidgets.QComboBox(self.centralwidget)
        self.eepromChooser.setGeometry(QtCore.QRect(120, 10, 86, 30))
        self.eepromChooser.setEditable(False)
        self.eepromChooser.setObjectName("eepromChooser")
        self.readE = QtWidgets.QPushButton(self.centralwidget)
        self.readE.setGeometry(QtCore.QRect(700, 10, 91, 31))
        self.readE.setObjectName("readE")
        self.writeE = QtWidgets.QPushButton(self.centralwidget)
        self.writeE.setGeometry(QtCore.QRect(700, 50, 91, 30))
        self.writeE.setObjectName("writeE")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 130, 781, 401))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 777, 397))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.eepromFile = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.eepromFile.setGeometry(QtCore.QRect(0, 0, 401, 401))
        self.eepromFile.setObjectName("eepromFile")
        self.outputLog = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.outputLog.setGeometry(QtCore.QRect(400, 0, 381, 401))
        self.outputLog.setObjectName("outputLog")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 10, 241, 31))
        self.label_2.setObjectName("label_2")
        self.loadFile = QtWidgets.QPushButton(self.centralwidget)
        self.loadFile.setGeometry(QtCore.QRect(10, 60, 121, 38))
        self.loadFile.setObjectName("loadFile")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(460, 10, 231, 36))
        self.lineEdit.setObjectName("lineEdit")
        self.verifyE = QtWidgets.QPushButton(self.centralwidget)
        self.verifyE.setGeometry(QtCore.QRect(700, 90, 91, 30))
        self.verifyE.setObjectName("verifyE")
        self.verifyE_2 = QtWidgets.QPushButton(self.centralwidget)
        self.verifyE_2.setGeometry(QtCore.QRect(700, 540, 91, 30))
        self.verifyE_2.setObjectName("verifyE_2")
        self.filenamelabel = QtWidgets.QLabel(self.centralwidget)
        self.filenamelabel.setGeometry(QtCore.QRect(140, 60, 551, 41))
        self.filenamelabel.setObjectName("filenamelabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 34))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp_2 = QtWidgets.QMenu(self.menubar)
        self.menuHelp_2.setObjectName("menuHelp_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAcerca_de_Eeprom = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de_Eeprom.setObjectName("actionAcerca_de_Eeprom")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuHelp_2.addAction(self.actionAcerca_de_Eeprom)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Elegir Eeprom:"))
        self.readE.setText(_translate("MainWindow", "Leer"))
        self.writeE.setText(_translate("MainWindow", "Escribir"))
        self.label_2.setText(_translate("MainWindow", "Nombre de Archivo para Guardar:"))
        self.loadFile.setText(_translate("MainWindow", "Cargar Archivo"))
        self.verifyE.setText(_translate("MainWindow", "Verificar"))
        self.verifyE_2.setText(_translate("MainWindow", "Borrar"))
        self.filenamelabel.setText(_translate("MainWindow", "Se ha cargado el archivo:"))
        self.menuFile.setTitle(_translate("MainWindow", "Archivo"))
        self.menuHelp_2.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionOpen.setText(_translate("MainWindow", "Abrir"))
        self.actionSave.setText(_translate("MainWindow", "Guardar"))
        self.actionAcerca_de_Eeprom.setText(_translate("MainWindow", "Acerca de Eeprom"))

